name: Builder

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build-job:
    name: Build
    runs-on: debian-bookworm
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Run build script
      run: (./build.sh -b)
    - name: Archive packages
      uses: actions/upload-artifact@v3
      with:
        name: Store .deb files
        path: build/*.deb
